In [1]:
import numpy as np

In [2]:
arr= np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr * arr 

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr -100

array([-99, -98, -97, -96, -95, -94, -93, -92, -91])

In [7]:
arr ** 2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
np.exp2(arr)

array([  2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])