In [21]:
import numpy as np

In [5]:
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [12]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [23]:
arr_2d= np.array([[5,10,15],[10,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [10, 25, 30],
       [35, 40, 45]])

In [24]:
arr_2d[0][0]

5

In [25]:
arr_2d[0]

array([ 5, 10, 15])

In [26]:
arr_2d[1,1]

25

In [27]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [28]:
arr_2d[:2]

array([[ 5, 10, 15],
       [10, 25, 30]])

In [33]:
arr= np.arange(1,15)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
arr> 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [32]:
arr = arr[arr > 5]
arr

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])