In [2]:

#Python array
my_list=[1,2,3,4]
my_list

[1, 2, 3, 4]

In [8]:
import numpy as np
arr=np.array(my_list)
arr

array([1, 2, 3, 4])

In [12]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
arr_mat= np.array(my_mat)
arr_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0,5,100)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [16]:
np.random.rand(4,4)

array([[0.54236446, 0.14454486, 0.21994968, 0.15851542],
       [0.89471572, 0.88229235, 0.08116095, 0.08353466],
       [0.2466952 , 0.45000633, 0.70082805, 0.95807228],
       [0.90600605, 0.55022146, 0.97234252, 0.18447324]])

In [36]:
arr=np.random.randint(0,50,30)
arr


array([47, 38,  4, 12, 23, 41, 13, 11, 22,  0, 22, 14, 43, 36, 31, 49,  4,
       41,  3, 39, 20, 11, 22,  5, 24, 19,  2, 16, 13,  2])

In [41]:
newaarr= arr.reshape(5,6)

In [42]:
newaarr.shape

(5, 6)